/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Boundry;
import Controller.CertaintyFactor;
import Controller.DempsterShafer;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class GejalaView extends javax.swing.JFrame {

    /**
     * Creates new form GejalaView
     */
    public GejalaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();
        jComboBox9 = new javax.swing.JComboBox<>();
        jComboBox10 = new javax.swing.JComboBox<>();
        jComboBox11 = new javax.swing.JComboBox<>();
        jComboBox12 = new javax.swing.JComboBox<>();
        jComboBox13 = new javax.swing.JComboBox<>();
        jComboBox14 = new javax.swing.JComboBox<>();
        jComboBox15 = new javax.swing.JComboBox<>();
        jComboBox16 = new javax.swing.JComboBox<>();
        jComboBox17 = new javax.swing.JComboBox<>();
        jComboBox18 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        teks = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tekss = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 16)); // NOI18N
        jLabel1.setText("SISTEM PAKAR DIAGNOSIS PENYAKIT STROKE");

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel2.setText("KET:");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel3.setText("halaman utama, silahkan tekan tombol dibawah");

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel4.setText("jika ingin ke halaman input data atau ke");

        jButton1.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jButton1.setText("Input Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jCheckBox1.setText("Penurunan kesadaran/cenderung mengantuk");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Kesulitan bicara/memahami pembicaraan");

        jCheckBox3.setText("Kelemahan di lengan atau di tungkai/kaki secara tiba-tiba");

        jCheckBox4.setText("Kesemutan/mati rasa pada wajah, lengan, atau tungkai/kaki");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jCheckBox5.setText("Kehilangan keseimbangan tubuh");

        jCheckBox6.setText("Kehilangan penglihatan,penglihatan menjadi kabur, atau gangguan lapangan penglihatan");

        jCheckBox7.setText("Sakit kepala hebat tiba-tiba");

        jCheckBox8.setText("Mual atau muntah");

        jCheckBox9.setText("Kesulitan menelan");

        jCheckBox10.setText("Kejang tanpa riwayat kejang sebelumnya");

        jCheckBox11.setText("Kehilangan kesadaran");

        jCheckBox12.setText("Kehilangan keterampilan motorik (gerak) halus seperti tidak bisa berjalan, tidak bisa menulis");

        jCheckBox13.setText("Kesulitan menulis atau membaca");

        jCheckBox14.setText("Kelainan pada rasa pengecapan");

        jCheckBox15.setText("Kelemahan pada bagian wajah secara tiba-tiba (mulut mencong,mulut mengot, kebas di pipi)");

        jCheckBox16.setText("Memiliki riwayat penyakit diabetes melitus (DM)");

        jCheckBox17.setText("Memiliki riwayat penyakit hipertensi");

        jCheckBox18.setText("Memiliki riwayat penyakit stroke sebelumnya");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tidak tahu", "sedikit yakin ", "cukup yakin ", "yakin", "sangat yakin" }));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tidak tahu", "sedikit yakin ", "cukup yakin ", "yakin", "sangat yakin" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tidak tahu", "sedikit yakin ", "cukup yakin ", "yakin", "sangat yakin", " ", " " }));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tidak tahu", "sedikit yakin", "cukup yakin", "yakin", "sangat yakin", " " }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tidak tahu", "sedikit yakin", "cukup yakin", "yakin", "sangat yakin " }));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tidak tahu", "sedikit yakin", "cukup yakin", "yakin ", "sangat yakin" }));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tidak tahu", "sedikit yakin", "cukup yakin", "yakin ", "sangat yakin" }));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tidak tahu", "sedikit yakin", "cukup yakin", "yakin", "sangat yakin" }));

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tidak tahu", "sedikit yakin", "cukup yakin", "yakin", "sangat yakin" }));

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tidak tahu", "sedikit yakin", "cukup yakin", "yakin", "sangat yakin" }));

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tidak tahu", "sedikit yakin", "cukup yakin", "yakin", "sangat yakin" }));

        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tidak tahu", "sedikit yakin", "cukup yakin", "yakin", "sangat yakin" }));

        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tidak tahu", "sedikit yakin ", "cukup yakin ", "yakin", "sangat yakin" }));

        jComboBox14.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tidak tahu", "sedikit yakin", "cukup yakin", "yakin ", "sangat yakin" }));

        jComboBox15.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tidak tahu", "sedikit yakin", "cukup yakin", "yakin", "sangat yakin" }));

        jComboBox16.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tidak tahu", "sedikit yakin", "cukup yakin", "yakin ", "sangat yakin" }));

        jComboBox17.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tidak tahu", "sedikit yakin", "cukup yakin", "yakin", "sangat yakin" }));

        jComboBox18.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tidak tahu", "sedikit yakin", "cukup yakin", "yakin", "sangat yakin" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCheckBox15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckBox1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckBox2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckBox10, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckBox11, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jCheckBox7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(jCheckBox8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCheckBox9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jCheckBox14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                    .addComponent(jCheckBox13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jCheckBox18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCheckBox17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCheckBox16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox6, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jCheckBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox3)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox4)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox5)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox6)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox7)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox8)
                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox9)
                    .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox10)
                    .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox11)
                    .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox12)
                    .addComponent(jComboBox12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox13)
                    .addComponent(jComboBox13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox14)
                    .addComponent(jComboBox14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox15)
                    .addComponent(jComboBox15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox16)
                    .addComponent(jComboBox16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox17)
                    .addComponent(jComboBox17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox18)
                    .addComponent(jComboBox18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel5.setText("Hasil Diagnosis dengan Metode Certainty Factor");

        teks.setColumns(20);
        teks.setRows(5);
        jScrollPane5.setViewportView(teks);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel6.setText("Hasil Diagnosis dengan Metode Dempster Shafer");

        tekss.setColumns(20);
        tekss.setRows(5);
        jScrollPane6.setViewportView(tekss);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel7.setText("Solusi:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Jika anda terdiagnosis penyakit stroke hemoragik atau stroke iskemik atau \npun stroke hemoragik dan iskemik,segera lakukan pemeriksaan lebih lanjut\nke dokter di klinik atau rumah sakit terdekat! Untuk meminimalisir penyakit \nstroke bertambah parah, ada beberapa pencegahan yang dapat dilakukan,yaitu:\n1. Menghindari faktor risiko seperti menjaga kualitas hidup dan menerapkan \n   pola hidup sehat\n2. Jika memiliki riwayat penyakit diabetes melitus(DM) atau hipertensi,makan\n   obat secara teratur dan kontrol ke dokter secara rutin\n3. Mengatur pola makan yang memenuhi kecukupan gizi dan nutrisi yang seimbang\n4. Melakukan olahraga secara teratur\n5. Jangan berobat terapi ke alternatif seperti mantri,dukun,akupuntur atau \n   pengobatan alternatif lainnya, tetapi segera temui tenaga medis atau dokter\n   dibidang saraf \n\n");
        jScrollPane4.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton3.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jButton3.setText("Back To Home");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton2.setText("Diagnosis");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel9.setText("Keterangan opsi nilai keyakinan dari gejala yang dipilih");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Tidak tahu : Jika anda pernah mengalami gejala hanya satu kali saja, dan riwayat penyakit hanya baru 1x pemeriksaan\nSedikit yakin : Jika anda jarang mengalami gejala atau anda pernah mengalami gejala 1-3x dlm sebulan, dan riwayat penyakit hanya baru 2x pemeriksaan\nCukup yakin: Jika anda kadang-kadang mengalami gejala atau anda pernah mengalami gejala 1-3x dlm 1 minggu, dan riwayat penyakit sudah 3x pemeriksaan\nYakin : Jika anda sering mengalami gejala atau anda pernah mengalami gejala gejala >3x dlm seminggu, dan riwayat penyakit sudah sampai 4x pemeriksaan\nSangat yakin : Jika anda selalu mengalami gejala atau anda pernah mengalami gejala hampir tiap hari:, dan riwayat penyakit sudah lebih dari 5x pemeriksaan");
        jScrollPane3.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 535, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel10.setText("SILAHKAN PILIH GEJALA YANG ANDA ALAMI BESERTA KEYAKINAN ANDA TERHADAP GEJALA YANG DIALAMI ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel10)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(1, 1, 1)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addGap(6, 6, 6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          ArrayList<Double> gejala=new ArrayList<>();
          ArrayList<Double> nilai_keyakinan=new ArrayList<>();
          ArrayList<String> pilihgejala = new ArrayList<>(); 
        if(jCheckBox1.isSelected()){
            gejala.add(1.0);
            if(jComboBox1.getSelectedItem().toString().equals("tidak tahu")){
                 nilai_keyakinan.add(0.2);
            }else if(jComboBox1.getSelectedItem().toString().equals("sedikit yakin")){
                nilai_keyakinan.add(0.4);
            }else if(jComboBox1.getSelectedItem().toString().equals("cukup yakin")){
                nilai_keyakinan.add(0.6);
            }else if(jComboBox1.getSelectedItem().toString().equals("yakin")){
                nilai_keyakinan.add(0.8);
            }else if(jComboBox1.getSelectedItem().toString().equals("sangat yakin")){
                nilai_keyakinan.add(1.0);
            }
            pilihgejala.add("1");            
           
        }else{
               gejala.add(0.0);
                nilai_keyakinan.add(0.0);
        }
            
        
        if(jCheckBox2.isSelected()){
            gejala.add(1.0);
            if(jComboBox2.getSelectedItem().toString().equals("tidak tahu")){
                 nilai_keyakinan.add(0.2);
            }else if(jComboBox2.getSelectedItem().toString().equals("sedikit yakin")){
                nilai_keyakinan.add(0.4);
            }else if(jComboBox2.getSelectedItem().toString().equals("cukup yakin")){
                nilai_keyakinan.add(0.6);
            }else if(jComboBox2.getSelectedItem().toString().equals("yakin")){
                nilai_keyakinan.add(0.8);
            }else if(jComboBox2.getSelectedItem().toString().equals("sangat yakin")){
                nilai_keyakinan.add(1.0);
            }
            pilihgejala.add("1");
        }else{
               gejala.add(0.0);
               nilai_keyakinan.add(0.0);
        }
        
        if(jCheckBox3.isSelected()){
            gejala.add(1.0);
            if(jComboBox3.getSelectedItem().toString().equals("tidak tahu")){
                 nilai_keyakinan.add(0.2);
            }else if(jComboBox3.getSelectedItem().toString().equals("sedikit yakin")){
                nilai_keyakinan.add(0.4);
            }else if(jComboBox3.getSelectedItem().toString().equals("cukup yakin")){
                nilai_keyakinan.add(0.6);
            }else if(jComboBox3.getSelectedItem().toString().equals("yakin")){
                nilai_keyakinan.add(0.8);
            }else if(jComboBox3.getSelectedItem().toString().equals("sangat yakin")){
                nilai_keyakinan.add(1.0);
            }
            pilihgejala.add("1");
            
        }else{
               gejala.add(0.0);
               nilai_keyakinan.add(0.0);
        }
        
        if(jCheckBox4.isSelected()){
            gejala.add(1.0);
            if(jComboBox4.getSelectedItem().toString().equals("tidak tahu")){
                 nilai_keyakinan.add(0.2);
            }else if(jComboBox4.getSelectedItem().toString().equals("sedikit yakin")){
                nilai_keyakinan.add(0.4);
            }else if(jComboBox4.getSelectedItem().toString().equals("cukup yakin")){
                nilai_keyakinan.add(0.6);
            }else if(jComboBox4.getSelectedItem().toString().equals("yakin")){
                nilai_keyakinan.add(0.8);
            }else if(jComboBox4.getSelectedItem().toString().equals("sangat yakin")){
                nilai_keyakinan.add(1.0);
            }
            pilihgejala.add("1");
            
        }else{
               gejala.add(0.0);
               nilai_keyakinan.add(0.0);
        }
        
        if(jCheckBox5.isSelected()){
            gejala.add(1.0);
            if(jComboBox5.getSelectedItem().toString().equals("tidak tahu")){
                 nilai_keyakinan.add(0.2);
            }else if(jComboBox5.getSelectedItem().toString().equals("sedikit yakin")){
                nilai_keyakinan.add(0.4);
            }else if(jComboBox5.getSelectedItem().toString().equals("cukup yakin")){
                nilai_keyakinan.add(0.6);
            }else if(jComboBox5.getSelectedItem().toString().equals("yakin")){
                nilai_keyakinan.add(0.8);
            }else if(jComboBox5.getSelectedItem().toString().equals("sangat yakin")){
                nilai_keyakinan.add(1.0);
            }
            pilihgejala.add("1");
        }else{
               gejala.add(0.0);
               nilai_keyakinan.add(0.0);
        }
        
        if(jCheckBox6.isSelected()){
            gejala.add(1.0);
            if(jComboBox6.getSelectedItem().toString().equals("tidak tahu")){
                 nilai_keyakinan.add(0.2);
            }else if(jComboBox6.getSelectedItem().toString().equals("sedikit yakin")){
                nilai_keyakinan.add(0.4);
            }else if(jComboBox6.getSelectedItem().toString().equals("cukup yakin")){
                nilai_keyakinan.add(0.6);
            }else if(jComboBox6.getSelectedItem().toString().equals("yakin")){
                nilai_keyakinan.add(0.8);
            }else if(jComboBox6.getSelectedItem().toString().equals("sangat yakin")){
                nilai_keyakinan.add(1.0);
            }
            pilihgejala.add("1");
            
        }else{
               gejala.add(0.0);
               nilai_keyakinan.add(0.0);
        }
        
        if(jCheckBox7.isSelected()){
            gejala.add(1.0);
            if(jComboBox7.getSelectedItem().toString().equals("tidak tahu")){
                 nilai_keyakinan.add(0.2);
            }else if(jComboBox7.getSelectedItem().toString().equals("sedikit yakin")){
                nilai_keyakinan.add(0.4);
            }else if(jComboBox7.getSelectedItem().toString().equals("cukup yakin")){
                nilai_keyakinan.add(0.6);
            }else if(jComboBox7.getSelectedItem().toString().equals("yakin")){
                nilai_keyakinan.add(0.8);
            }else if(jComboBox7.getSelectedItem().toString().equals("sangat yakin")){
                nilai_keyakinan.add(1.0);
            }
            pilihgejala.add("1");
        }else{
               gejala.add(0.0);
               nilai_keyakinan.add(0.0);
        }
        
        if(jCheckBox8.isSelected()){
            gejala.add(1.0);
            if(jComboBox8.getSelectedItem().toString().equals("tidak tahu")){
                 nilai_keyakinan.add(0.2);
            }else if(jComboBox8.getSelectedItem().toString().equals("sedikit yakin")){
                nilai_keyakinan.add(0.4);
            }else if(jComboBox8.getSelectedItem().toString().equals("cukup yakin")){
                nilai_keyakinan.add(0.6);
            }else if(jComboBox8.getSelectedItem().toString().equals("yakin")){
                nilai_keyakinan.add(0.8);
            }else if(jComboBox8.getSelectedItem().toString().equals("sangat yakin")){
                nilai_keyakinan.add(1.0);
            }
            pilihgejala.add("1");
        }else{
               gejala.add(0.0);
               nilai_keyakinan.add(0.0);
        }
        
        if(jCheckBox9.isSelected()){
            gejala.add(1.0);
            if(jComboBox9.getSelectedItem().toString().equals("tidak tahu")){
                 nilai_keyakinan.add(0.2);
            }else if(jComboBox9.getSelectedItem().toString().equals("sedikit yakin")){
                nilai_keyakinan.add(0.4);
            }else if(jComboBox9.getSelectedItem().toString().equals("cukup yakin")){
                nilai_keyakinan.add(0.6);
            }else if(jComboBox9.getSelectedItem().toString().equals("yakin")){
                nilai_keyakinan.add(0.8);
            }else if(jComboBox9.getSelectedItem().toString().equals("sangat yakin")){
                nilai_keyakinan.add(1.0);
            }
            pilihgejala.add("1");
        }else{
               gejala.add(0.0);
               nilai_keyakinan.add(0.0);
        }
        
        if(jCheckBox10.isSelected()){
            gejala.add(1.0);
            if(jComboBox10.getSelectedItem().toString().equals("tidak tahu")){
                 nilai_keyakinan.add(0.2);
            }else if(jComboBox10.getSelectedItem().toString().equals("sedikit yakin")){
                nilai_keyakinan.add(0.4);
            }else if(jComboBox10.getSelectedItem().toString().equals("cukup yakin")){
                nilai_keyakinan.add(0.6);
            }else if(jComboBox10.getSelectedItem().toString().equals("yakin")){
                nilai_keyakinan.add(0.8);
            }else if(jComboBox10.getSelectedItem().toString().equals("sangat yakin")){
                nilai_keyakinan.add(1.0);
            }
            pilihgejala.add("1");
        }else{
               gejala.add(0.0);
               nilai_keyakinan.add(0.0);
        }
        
        if(jCheckBox11.isSelected()){
            gejala.add(1.0);
            if(jComboBox11.getSelectedItem().toString().equals("tidak tahu")){
                 nilai_keyakinan.add(0.2);
            }else if(jComboBox11.getSelectedItem().toString().equals("sedikit yakin")){
                nilai_keyakinan.add(0.4);
            }else if(jComboBox11.getSelectedItem().toString().equals("cukup yakin")){
                nilai_keyakinan.add(0.6);
            }else if(jComboBox11.getSelectedItem().toString().equals("yakin")){
                nilai_keyakinan.add(0.8);
            }else if(jComboBox11.getSelectedItem().toString().equals("sangat yakin")){
                nilai_keyakinan.add(1.0);
            }
            pilihgejala.add("1");
        }else{
               gejala.add(0.0);
               nilai_keyakinan.add(0.0);
        }
        
        if(jCheckBox12.isSelected()){
            gejala.add(1.0);
            if(jComboBox12.getSelectedItem().toString().equals("tidak tahu")){
                 nilai_keyakinan.add(0.2);
            }else if(jComboBox12.getSelectedItem().toString().equals("sedikit yakin")){
                nilai_keyakinan.add(0.4);
            }else if(jComboBox12.getSelectedItem().toString().equals("cukup yakin")){
                nilai_keyakinan.add(0.6);
            }else if(jComboBox12.getSelectedItem().toString().equals("yakin")){
                nilai_keyakinan.add(0.8);
            }else if(jComboBox12.getSelectedItem().toString().equals("sangat yakin")){
                nilai_keyakinan.add(1.0);
            }
            pilihgejala.add("1");
        }else{
               gejala.add(0.0);
               nilai_keyakinan.add(0.0);
        }
        
        if(jCheckBox13.isSelected()){
            gejala.add(1.0);
            if(jComboBox13.getSelectedItem().toString().equals("tidak tahu")){
                 nilai_keyakinan.add(0.2);
            }else if(jComboBox13.getSelectedItem().toString().equals("sedikit yakin")){
                nilai_keyakinan.add(0.4);
            }else if(jComboBox13.getSelectedItem().toString().equals("cukup yakin")){
                nilai_keyakinan.add(0.6);
            }else if(jComboBox13.getSelectedItem().toString().equals("yakin")){
                nilai_keyakinan.add(0.8);
            }else if(jComboBox13.getSelectedItem().toString().equals("sangat yakin")){
                nilai_keyakinan.add(1.0);
            }
            pilihgejala.add("1");
        }else{
               gejala.add(0.0);
               nilai_keyakinan.add(0.0);
        }
        
        if(jCheckBox14.isSelected()){
            gejala.add(1.0);
            if(jComboBox14.getSelectedItem().toString().equals("tidak tahu")){
                 nilai_keyakinan.add(0.2);
            }else if(jComboBox14.getSelectedItem().toString().equals("sedikit yakin")){
                nilai_keyakinan.add(0.4);
            }else if(jComboBox14.getSelectedItem().toString().equals("cukup yakin")){
                nilai_keyakinan.add(0.6);
            }else if(jComboBox14.getSelectedItem().toString().equals("yakin")){
                nilai_keyakinan.add(0.8);
            }else if(jComboBox14.getSelectedItem().toString().equals("sangat yakin")){
                nilai_keyakinan.add(1.0);
            }
            pilihgejala.add("1");
        }else{
               gejala.add(0.0);
               nilai_keyakinan.add(0.0);
        }
        
        if(jCheckBox15.isSelected()){
            gejala.add(1.0);
            if(jComboBox15.getSelectedItem().toString().equals("tidak tahu")){
                 nilai_keyakinan.add(0.2);
            }else if(jComboBox15.getSelectedItem().toString().equals("sedikit yakin")){
                nilai_keyakinan.add(0.4);
            }else if(jComboBox15.getSelectedItem().toString().equals("cukup yakin")){
                nilai_keyakinan.add(0.6);
            }else if(jComboBox15.getSelectedItem().toString().equals("yakin")){
                nilai_keyakinan.add(0.8);
            }else if(jComboBox15.getSelectedItem().toString().equals("sangat yakin")){
                nilai_keyakinan.add(1.0);
            }
            pilihgejala.add("1");
        }else{
               gejala.add(0.0);
               nilai_keyakinan.add(0.0);
        }
        
        if(jCheckBox16.isSelected()){
            gejala.add(1.0);
            if(jComboBox16.getSelectedItem().toString().equals("tidak tahu")){
                 nilai_keyakinan.add(0.2);
            }else if(jComboBox16.getSelectedItem().toString().equals("sedikit yakin")){
                nilai_keyakinan.add(0.4);
            }else if(jComboBox16.getSelectedItem().toString().equals("cukup yakin")){
                nilai_keyakinan.add(0.6);
            }else if(jComboBox16.getSelectedItem().toString().equals("yakin")){
                nilai_keyakinan.add(0.8);
            }else if(jComboBox16.getSelectedItem().toString().equals("sangat yakin")){
                nilai_keyakinan.add(1.0);
            }
            pilihgejala.add("1");
        }else{
               gejala.add(0.0);
               nilai_keyakinan.add(0.0);
        }
        
        if(jCheckBox17.isSelected()){
            gejala.add(1.0);
            if(jComboBox17.getSelectedItem().toString().equals("tidak tahu")){
                 nilai_keyakinan.add(0.2);
            }else if(jComboBox17.getSelectedItem().toString().equals("sedikit yakin")){
                nilai_keyakinan.add(0.4);
            }else if(jComboBox17.getSelectedItem().toString().equals("cukup yakin")){
                nilai_keyakinan.add(0.6);
            }else if(jComboBox17.getSelectedItem().toString().equals("yakin")){
                nilai_keyakinan.add(0.8);
            }else if(jComboBox17.getSelectedItem().toString().equals("sangat yakin")){
                nilai_keyakinan.add(1.0);
            }
            pilihgejala.add("1");
        }else{
               gejala.add(0.0);
               nilai_keyakinan.add(0.0);
        }
        
        if(jCheckBox18.isSelected()){
            gejala.add(1.0);
            if(jComboBox18.getSelectedItem().toString().equals("tidak tahu")){
                 nilai_keyakinan.add(0.2);
            }else if(jComboBox18.getSelectedItem().toString().equals("sedikit yakin")){
                nilai_keyakinan.add(0.4);
            }else if(jComboBox18.getSelectedItem().toString().equals("cukup yakin")){
                nilai_keyakinan.add(0.6);
            }else if(jComboBox18.getSelectedItem().toString().equals("yakin")){
                nilai_keyakinan.add(0.8);
            }else if(jComboBox18.getSelectedItem().toString().equals("sangat yakin")){
                nilai_keyakinan.add(1.0);
            }
            pilihgejala.add("1");
        }else{
               gejala.add(0.0);
               nilai_keyakinan.add(0.0);
        }
        boolean check=false;
        for (int i = 0; i < gejala.size(); i++) {
            if (gejala.get(i)==1.0) {
                check=true;
            }
        }
        if(check==false){
            JOptionPane.showMessageDialog(null, "Silahkan pilih gejala ");
        }
        else if(pilihgejala.size()==1){
            JOptionPane.showMessageDialog(null, "Silahkan pilih gejala minimal 2");
        }
        else{
        ArrayList<ArrayList> data_uji=new ArrayList<>();
        ArrayList<ArrayList> data_uji_keyakinan=new ArrayList<>();
         gejala.add(0.0);
        data_uji.add(gejala);
        data_uji_keyakinan.add(nilai_keyakinan);
        
        
        CertaintyFactor cf = new CertaintyFactor();
        cf.do_certainty_factor(data_uji,data_uji_keyakinan);
        ArrayList<String> hasil = cf.get_hasil();
        ArrayList<Double> bobot = cf.get_bobot();
        int i=0;
//        DefaultTableModel data_header = new DefaultTableModel(new String[]{
//            "Jenis Penyakit",
//            "Nilai Kepercayaan/Keyakinan"
//        }, 0);
//        jTable1.setModel(data_header); // set table header
//        for (int i = 0; i < hasil.size(); i++) {
            String temp=hasil.get(i);
            if(temp.toLowerCase().equals("p1")){
                temp="Stroke Hemoragik";
            }else if(temp.toLowerCase().equals("p2")){
                 temp="Stroke Iskemik";
            }
//            data_header.addRow(new Object[]{
//                temp,
//                bobot.get(i)+"%"
//            });
        //}
         teks.setText(
             "Jenis Penyaki:"+temp+"\n"+
             "Nilai Keyakinan/Kepercayaan:"+bobot.get(i)+"%"
            );
        
        DempsterShafer ds = new DempsterShafer();
        ds.do_dempster_shafer(data_uji);
        ArrayList<String> hasil_ds = ds.get_hasil();
        ArrayList<Double> bobot_ds = ds.get_bobot();

//        DefaultTableModel data_header_ds = new DefaultTableModel(new String[]{
//            "Jenis Penyakit",
//            "Nilai Kepercayaan/Keyakinan"
//        }, 0);
//        jTable2.setModel(data_header_ds); // set table header
//        for (int i = 0; i < hasil_ds.size(); i++) {
            String temp1=hasil_ds.get(i);
            if(temp1.toLowerCase().equals("p1")){
                temp1="Stroke Hemoragik";
            }else if(temp1.toLowerCase().equals("p2")){
                 temp1="Stroke Iskemik";
            }
            else{
                temp1="Stroke Hemoragik,Stroke Iskemik";
            }
//            data_header_ds.addRow(new Object[]{
//                temp,
//                bobot_ds.get(i)*100+"%"
//            });
       // }
            tekss.setText(
                 "Jenis Penyaki:"+temp1+"\n"+
                "Nilai Keyakinan/Kepercayaan:"+(bobot_ds.get(i)*100)+"%"
    );   
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new DataView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       homeview hv = new homeview();
       hv.show();
       this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GejalaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GejalaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GejalaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GejalaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GejalaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox12;
    private javax.swing.JComboBox<String> jComboBox13;
    private javax.swing.JComboBox<String> jComboBox14;
    private javax.swing.JComboBox<String> jComboBox15;
    private javax.swing.JComboBox<String> jComboBox16;
    private javax.swing.JComboBox<String> jComboBox17;
    private javax.swing.JComboBox<String> jComboBox18;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea teks;
    private javax.swing.JTextArea tekss;
    // End of variables declaration//GEN-END:variables
}
